### ISSUE TITLE
Content missing

### ISSUE THREAD

**Issue by d2s** [futurice/lean-service-creation-kit#1]
On the [project website](https://futurice.github.io/lean-service-creation-kit/#open_source), text tells that:
_“You can as well download the full LSC Toolkit package directly.”_

Sadly that is not possible as the download contains only `README.md` and `.gitignore`.

Hopefully the actual content would be published at some point of time, as it would be helpful to many.

**Comment by ttur** [comment]
Thank you for pointing this out, and apologies for our tardiness. Now the site content is finally in place and the LSC.zip under the master branch contains the relevant documents.
